import {
  LucideActivity,
  LucideCalendarCheck2,
  LucideChevronDown,
  LucideClock,
  LucideFolder,
  LucideLayers,
  LucideLogOut,
  LucideMessageSquare,
  LucideMessageSquarePlus,
  LucideMessageSquareX,
  LucideMoon,
  LucideSun,
  LucideTag,
  LucideUser,
  LucideUserCheck,
  LucideUserStar,
  LucideUsers,
  LucideX,
  provideLucideIcons,
} from '@lucide/angular';

export const lucideAppIconsProvider = provideLucideIcons(
  LucideActivity,
  LucideCalendarCheck2,
  LucideChevronDown,
  LucideClock,
  LucideFolder,
  LucideLayers,
  LucideLogOut,
  LucideMessageSquare,
  LucideMoon,
  LucideSun,
  LucideTag,
  LucideUser,
  LucideUserCheck,
  LucideUserStar,
  LucideUsers,
  LucideX,
  LucideMessageSquarePlus,
  LucideMessageSquareX,
);
